ignore_sellers = {"de vinylloods", "Who's Your Daddy Records", "Concerto Recordstore", "De Vinylloods",
                  "de vinylloods gevraagd", "Tweedehands CD", "Velvet Music Eindhoven", "VARIAWORLD",
                  "NICE_PRICE_VINYL", "Vinylplaten.com", "VARIAWORLD webwinkel",
                  "de vinylloods gezocht vinyl platen collecties", "Simply-listening", "Nonstop Records",
                  "Collectorsheaven.nl", "vinylvrienden", "japie records", "Catawiki B.V.", "Golden Oldies",
                  "Moody!!", "www.RigeShop.com", "Zap Records", "45Toeren", "vinylvrienden", "BookSpot",
                  "Vinylplaten", "OldRecordz", "voordeelshopregina", "J M", "Boschrock", "oldscool recordz",
                  "Jan44", "Verzamelaar", "Caron", "ri.aker", "Vinyl Hobbyist", "SoundConnexion", "s.d.j",
                  "DGMoutlet.nl", "Vinylvlodrop", "Bjorn", "Classical_Disk", "L'animal", "Blackvinyl.nl",
                  "winkel", "A.R.S.", "de vinylloods LP / lps gevraagd gezocht", "Vinylshop FH", "engels",
                  "vinyl45", "PEACE4UKRAINE", "Enjoy The Music", "kees", "Knabbel!", "Art_P", "U3", "Signs USA",
                  "Noppes Kringloopwinkel", "Bigv.", "ERecords", "Project-38 Music", "jolink", "Ruby",
                  "jack's vinyl music", "bernja", "Needle Dose Music", "Hans", "Raymond", "Angela en Tim Middeldorp",
                  "Harry Palmer Vintage", "Gert-Jan", "Lientje", "Marjanlps", "Wardt", "Brothers", "Mr. Vinyl",
                  "Leesboekenwinkel nl", "Records on Vinyl", "RUD2?", "Mateo520", "Egon", "noturnsoutlet", "G.K.",
                  "Selected Sounds", "Jan Boonstra", "ALBEPRO", "SteffenC Music", " Acraft DJ furniture", "Talmricht",
                  "Artistic Recordstore", "Frank’s Vinyl", "PLATENREUS (OFFICIAL)", "Vip Records", "Bunnie",
                  "Even-Tijdcentrum V.O.F.", "www.lpwinkel.nl", "De Waterput", "BOGAMO", "keietrekker",
                  "De Platenverzamelaar", "Disc-records-Webshop", "Bob's Vinyl",
                  "KAY'S ODYSSEY Maxi-single inkoop Wagenberg N.Br.", "KAY KOOPT AL UW LP's & CD's !!!!",
                  "VINYL INKOOP NEDERLAND", "O", " JUKEBOXSINGLES", "recordspecialist", "noturns",
                  "KAY'S ODYSSEY THE EXPERIENCE", "Boer", "DBMERCH", "spijk-records", "Mijn Platenzaak",
                  "Klaas Dijkstra", "VCRShop.com", "Reway", "Robbie's Records", "Robbies Records", "Jennen-Schwarz",
                  "Melvyn", " JBeetje", "kees van meurs", "vinylplaten.com", "'t olde gre-j", "JBeetje",
                  "Pandjeshuis Friesland", "Kay's Odyssey The Experience Wagenberg N.Br.", "Marktplaats - BELGIË",
                  "erkeland", "flowerman", "Bennies Fifties/Fifties Store", "Music Shop Kore", "Variaworld.nl",
                  "Dennis Records", "Piratenteam", "GOOD TIMES", "mad-gameshop.com", "Selected Sounds Inkoopdagen",
                  "ID-MP", "45 rpm-liefhebber", "Patrick Janssen", "Boeck", "wuvyou", "RedmountainRecords",
                  "Dave sr.", "45toeren", "singelstreet", "frans els", "coriensvinyl", "1990", "Pike - Vinyl Vibes",
                  "g. op Zolder", "Bosman", "Johnny", "Gerard", "Peter1974", "Pepernoot", "VinylHobbyist.nl",
                  "Timeless Music", "keesies", "HA~VO Records", "Secondshand Vinyl & Cd", "Spin the black circle",
                  "mv morgenster", "Verzamel lp", "Euroshop", "fokke", "johanna", "George", "A.T.", "rosie",
                  "Rutten van Zon", "liebregts", "Hr Vos", "Klassieker61", "bobg", "J.O.H.A.N.", "Roelie",
                  "Hans D.", "marc_020", "steenkist", "ans", "DIANA", "johan sanders", "LT", "m. van atten", "JoannaTG",
                  "SD", "Johnklijn", "jacpevinyl", "P. Jaspers", "Topvinylshop", "A. Bastiaanssen", "Laura H",
                  "Stampie", "Vinyl Uit Tiel", "Ernst", "hollandserkanhetniet", "Music-Forever", "GJN",
                  "Floris en Kelly", "Fonky", "Hendrap", "JUKEBOXSINGLES", "HANS SUPER 8 FILMS", "Ad Riezebos",
                  "LP Verzameling", "Moshover", "k sauer", "Disc-records+vintage", "NOT DEAD ENOUGH", " More4Less",
                  "U2stay", "Chris", "Into It Records", "nicko-v", "Pieter Vermaas", "Vinyl & Munten", "adriaan",
                  "Qwen", "Nooddienst 24/7", "The Collector", "lisa", "Platen en Co.", "nienke en wullum",
                  "Plaatwerk Design", "Cassette Digitalisatie", "vinylliefhebber", "Kaddy", "Funk1"

                  }

ignore_artists = {"beatles", "vannelli", "joan baez", "alquin", "roy orbison", "cliff richard", "astrud gilberto",
                  "leo sayer", "pat boone", "ray conniff", "rolling stones", "demis roussos", "elvis presley",
                  "julio iglesias", "john lennon", "dolly dots", "herman brood", "dizzy gillespie", "fats domino",
                  "neil diamond", "leo kottke", "neil sedaka", "timi yuro", "john mayall", "rod stewart",
                  "creedence clearwater", "marillion", "jan akkerman", "ray charles", "dionne warwick", "buddy holly",
                  "albert hammond", "janis joplin", "alan stivell", "gerry rafferty", "normaal", "erroll garner",
                  "abba", "allman brothers", "vangelis", "massada", "commodores", "louis armstrong", "count basie",
                  "glenn miller", "sergio mendes", "james brown", "ike tina", "harry sacksioni", "udo jurgens",
                  "billy preston", "chaka khan", "belafonte", "fausto papetti", "mouskouri", "olivia newton",
                  "james last", "jim reeves", "johnny meyer", "chubby checker", "aretha franklin", "ike & tina",
                  "linda ronstadt", "fairport convention", "ink spots", "george-benson", "shirley bassey",
                  "frank zappa", "perry como", "mahalia jackson", "alison moyet", "kim wilde", "lotus eaters",
                  "electric light orchestra", "vicky leandros", "jim croce", "matt bianco", "petula clark",
                  "kerstmis", "moody blues", "stevie wonder", "roger whittaker", "rory gallagher", "mireille mathieu",
                  "al stewart", "joe bonamassa", "donovan", "paul anka", "dolly parton", "modern talking",
                  "manfred mann", "lee towers", "edith piaf", "janet jackson", "ten years after", "miles davis",
                  "john coltrane", "chris hinze", "bruce springsteen", "gary glitter", "jose feliciano",
                  "ramses shaffy", "roberta flack", "randy newman", "flairck", "bette midler", "tom jones",
                  "ray parker", "pointer sisters", "saturday night fever", "billy joel", "john denver", "dubliners",
                  "branduardi", "wishbone ash", "david bowie", "nina simone", "everly brothers", "bing crosby",
                  "ike and tina", "lionel richie", "gilbert becaud", "mel and kim", "gloria gaynor", "graham nash",
                  "harry nilsson", "janis ian", "ennio morricone", "tom waits", "canned heat", "spotnicks",
                  "earth and fire", "steve winwood", "boney m", "emerson lake and palmer", "klaatu", "spandau ballet",
                  "the byrds", "chuck berry", "mike oldfield", "thelonious monk", "rickie lee jones", "don mclean",
                  "blue diamonds", "communards", "herbie hancock", "marvin gaye", "the motions", "joan armatrading",
                  "nils lofgren", "golden earring", "ella fitzgerald", "joe walsh", "edward woodward", "ferre grignard",
                  "shocking blue", "fischer-z", "roger witthaker", "the spots", "vader abraham", "magna carta",
                  "george baker", "vera lynn", "tumbleweeds", "donny osmond", "rob de nijs", "kayak", "gruppo sportivo",
                  "the stylistics", "heino", "candy dulfer", "aznavour", "the hollies", "spargo", "marie laforet",
                  "jaap dekker", "herb alpert", "anita meyer", "paul mauriat", "randy crawford", "the platters",
                  "peggy lee", "john hiatt", "sarah vaughan", "gerry mulligan", "ekseption", "ringo starr",
                  "shakin stevens", "kim fowley", "eminem", "rogier van otterloo", "errol garner", "stan getz",
                  "francis goya", "garland jeffreys", "terence trent", "graham parker", "moustaki", "dave brubeck",
                  "yves duteil", "hugues aufray", "simon and garfunkel", "simon & garfunkel", "osmonds", "adele",
                  "christoffer cross", "christopher cross", "johnny winter", "thielemans", "little richard",
                  "new seekers", "mink deville", "mantovani", "percy sledge", "les humphries", "billy ocean",
                  "shakatak", "robert palmer", "jools holland", "francoise hardy", "mamas and papas", "donna summer",
                  "humperdinck", "lionel hampton", "peter maffay", "andre hazes", "teach-in", "jesus christ superstar",
                  "billie holiday", "django reinhardt", "carole king", "jerry lee lewis", "grand funk", "bill haley",
                  "steve miller", "the runaways", "milli vanilli", "feliciano", "ellen foley" "johnny hallyday",
                  "juliette greco", "oscar peterson", "robert long", "franck pourcel", "irolt", "the walker brothers",
                  "carolyne mas", "nik kershaw", "rick wakeman", "ben webster", "flying burrito", "ry cooder",
                  "boudewijn de groot", "herbie mann", "maywood", "barrelhouse", "lalo schifrin", "frank pourcel",
                  "cuby and the blizzards", "stephen stills", "the ritchie family", "bzn", "theodorakis",
                  "mathilde santing", "barry white", "fay lovsky", "ellen foley", "jimi hendrix", "joe jackson",
                  "doris day", "amanda lear", "jacques brel", "billy vaughn", "deodato", "duke ellington",
                  "george benson", "reo speedwagon", "crosby stills", "mungo jerry", "joni mitchell", "barclay james",
                  "phil manzanera", "suzanne vega", "rick astley", "pat travers", "ted nugent", "toyah",
                  "yngwie malmsteen", "otis redding", "billie holliday", "led zeppelin", "richard clayderman",
                  "james galway", "the kinks", "zappa", "strawbs", "the ventures", "andy williams", "tielman brothers",
                  "vollenweider", "graham bonnet", "zarah leander", "the nylons", "tavares", "kaempfert",
                  "liesbeth list", "connie francis", "xanadu", "mel kim", "amy winehouse", "procol harum",
                  "art garfunkel", "paul young", "bee gees", "astor piazzolla", "piet veerman", "roger whittakker",
                  "kamahl", "ricky nelson", "wim sonnevelds", "heintje", "hollies", "labi siffre", "eddie cochran",
                  "thijs van leer", "brenda lee", "dr hook", "emerson lake palmer", "boomtown rats",
                  "marshall tucker band", "commander cody", "daniel sahuleka", "tee set", "del shannon", "beach boys",
                  "lovin spoonful", "peter frampton", "mick jagger", "nat king cole", "johnny and the hurriccanes",
                  "tommy the who", "derek and the dominos", "nick lowe", "howard jones", "wet wet wet",
                  "wes montgomery", "schlager", "britney spears", "rose royce", "dory previn", "danny vera",
                  "elly rikkert", "benny goodman", "the supremes", "wil tura", "klaus schulze", "kokomo",
                  "nancy sinatra", "goombay dance band", "sly the family", "bob segers", "toontje lager", "johnny otis",
                  "cuby blizzards", "kool and the gang", "emerson lake palmer", "dr. hook", "mel & kim", "carpenters",
                  "bangles", "atomic rooster", "osibisa", "dave mason", "buddy guy", "kids from fame", "trini lopez",
                  "keith jarrett", "nat cole", "prince purple rain", "yes tales from", "yes fragile", "yes tomato",
                  "yes relayer", "frida boccara", "michel fugain", "herman van veen", "jaap fischer", "dean martin",
                  "harpers bizarre", "julien clerc", "emerson lake", "paolo conte", "jeff beck",
                  "quicksilver messenger", "byrds", "rebroff", "malando", "malmsteen", "rhoda scott", "cuby blizzards",
                  "shakin arrows", "gene pitney", "duane eddy", "papetti", "frank boeijen", "wespenbestrijding",
                  "wim sonneveld", "ruud hermans", "kc the sunshine", "eric burdon", "julian clerc", "four tops",
                  "cozy powell", "the who tommy", "bellamy brothers", "kool the gang", "kinderen voor kinderen",
                  "spencer davis group", "pierre rapsat", "urbanus", "pat benatar", "baccara", "leandros", "bilitis",
                  "pink floyd", "michael jackson", "henry mancini", "stray cats", "alan price", "johnny cash",
                  "doobie brothers", "lovin spoonful", "leni lovich", "manhattan transfer", "frank duval",
                  "shakin' stevens", "small faces", "malcolm mclaren", "rick james", "euson", "john fogerty",
                  "jackson browne", "dan fogelberg", "bob seger", "freddy quinn", "oscar harris", "madonna",
                  "bonzo dog band", "hotel california", "frida", "lovin’ spoonful", "johnny rivers", "ofarim",
                  "todd rundgren", "jemaine jackson", "rare earth", " booker t.", "lynn anderson", " freddie jackson",
                  "style council", "yazz", "maurice white", "patricia paay", " j.j. cale", "jj cale", "badfinger",
                  "barrabas", "wham", "olivia rodrigo", "the babys", "hit explosion", " gladys knight", "the cats",
                  "kilima hawaiians", "lovin' spoonful", "wim kan", "al jarreau", "karla bonoff", "little river band",
                  "koos alberts", "gordon lightfoot", "ananta", "blow monkeys", "jj cale", "feargal sharkey",
                  "roger daltrey", "country gazette", "miller band", "conniff", "lenny kuhr",
                  "andrew lloyd webber", "bostjan konecnik", "floyd cramer", "dave edmunds", "johan stollz",
                  "don johnson", "michel legrand", "glenn frey", "iron butterfly", "louis van dijk", "oscar harris",
                  "rod mckuen", "jon lord", "alvin lee", "24 carat purple", "dr.hook", "caravelli",
                  "long tall ernie", "village people", "outlandos d'amour", "reggatta de blanc", "zenyatta mondatta",
                  "lucille starr", "mama's & papa's", "marti webb", "rita coolidge", "dalida", "catch bull at four",
                  "frankie goes to hollywood", "alvin stardust", "mary roos", "laura branigan", "glen campbell",
                  "frank & mirella", "sister sledge", " o'sullivan", "hammond and west", "yazoo", "john spencer",
                  "righteous brothers", "clouseau", " 461 ocean", "johnny hallyday", "benny neyman",
                  "clearwater revival", "guys 'n' dolls", "frankie laine", "tee-set", "kid creole", "lene lovich",
                  "bonnie pointer", "cock robin", "peter alexander", "adamo", "russ ballard", "sweet d'buster",
                  "sam cooke", "cerrone", "anthony phillips", "freddy breck", "georges brassens", "grace slick",
                  "gregory isaacs", "harry chapin", "band on the run", "kristy maccoll", "geils band", "sahuleka",
                  "kiss dynasty", "roy black", "toon hermans", "henk elsink", "average white band", "bruce hornsby",
                  "jo spears", "jacketti", "david gates", "joe dassin", "be bop deluxe", "aphrodite's child",
                  "dirty dancing", "anne murray", "paul hardcastle", "mamas and the papas", "tony esposito",
                  "johnnie ray", "james taylor", "roy buchanan", "bassie & adriaan", "zamfir", "black uhuru",
                  "johnny logan", "peter tosh", "natalie cole", "rudolf schock", "the last waltz", "love over gold",
                  "lloyd price", "henk wijngaard", "ian matthews", "eberhard schoener", "dutch pop giants",
                  "jim capaldi", "rondo veneziano", "gerard joling", "bollock brothers", "fred stuger",
                  "bruce cockburn", "smokey robinson", "oldies but goldies", "godley & creme", "the animals",
                  "miriam makeba", "madman across", "daryl hall", "gram parsons", "crosby, stills", "chieftains",
                  "deodata", "jon anderson", "mezzoforte", "hair of the dog", "thomas dolby", "strauss family",
                  "ariana grande", "barry manilow", "mcguinn clark", "jumping jewels", "topographic ocean",
                  "principle of moments", "queen budokan", "johnny nash", "cor steyn", "andre moss", "mike batt",
                  "john woodhouse", "prince and the revolution", "peter hammill", "jobriath", "la toya",
                  "heep wonderworld", "rasa everything", "lambada", "buddy odor", "gentle giant", "santa esmeralda",
                  "turner overdrive", "fatal flowers", "manzanera", "stealers wheel", "bobby womack", "peter griffin",
                  "dusty springfield", "chi coltrane", "veronica souvenir", "bobby whitlock", "traveling wilburys",
                  "crosby and nash", "steppenwolf", "caterina valente", "michael cassidy", "swinging blue jeans",
                  "thick as a brick", "bohannon", "warm aanbevolen", "bloody tourists", "divinyls", "brian hyland",
                  "marty robbins", "gladys knight", "zangeres zonder naam", "johnny and the hurricanes",
                  "sheena easton", "sonny & cher", "bananarama", "porgy and bess", "beegees", "peter schilling",
                  "highway chile", "sly & the family", "anita baker", "roy ayers", "elkie brooks", "fairport",
                  "bow wow", "de maskers", "duncan browne", "the who", "leon russell", "platenplankie",
                  "bobby vinton", "southside johnny", "billy squier", "gary wright", "john cougar", "tol hansse",
                  "goldsboro", "georgie fame", "greg kihn", "thelma houston", "sutherland brothers",
                  "harry holland", "golden hit parade", "andre van duin", "lake & palmer", "band last waltz",
                  "mike rutherford", "richard marx"
                  }

ignore_besellers = {
                    "VINYLKITCHEN", "Variaworld", "the best agreement", "Bailesti", "HENSPATRICK",
                    "Who's Your Daddy Records", "janbeton", "VinylHobbyist", "Fonorama", "Vinylfreak",
                    "Vinylzoektocht", "BOGAMO", "Music Mania Gent", "P90", "Carlos Carlos", "Bellair",
                    "Lc vinyl & Vintage", "CH Laeremans", "ROGER C. WYBOUW", "elviske", "LEESBOEKENWINKEL NL",
                    "Boutique Oxalys", "VAN SAENE ANDRE", "BDW", "fify", "Balcony", "Fonky", "Rom", "vinylplaten.com",
                    "ARIELLE", "gandalf", "Old Vinyl"
}


if __name__ == "__main__":
    print("neil diamond" in ignore_artists)
